services:
  starknet:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: starknet-re7labs
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: ["yarn", "start"]