version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: re7-labs-postgres
    environment:
      POSTGRES_DB: re7labs
      POSTGRES_USER: re7labs
      POSTGRES_PASSWORD: re7labs123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: re7-labs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
