name: Build and publish
on:
  push:
    branches:
      - main

jobs:
  lint_and_build:
    name: Performs linting, formatting, building and deploy
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      WORKDIR: ${{ secrets.WORKDIR }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --legacy-peer-deps

      - name: Set env
        run: echo "${{secrets.ENV_PROD }}" > .env.local
          
      - name: Run linting check
        run: yarn run lint:check

      - name: Check formatting
        run: yarn run format:check

      - name: Build
        run: yarn run build

      - name: Set ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host starknet
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Deploy with Rsync
        run: |
          rsync -avz -e ssh .next starknet:$WORKDIR/.next
          rsync -avz -e ssh public starknet:$WORKDIR/public
          rsync -avz -e ssh node_modules starknet:$WORKDIR/node_modules
          rsync -avz -e ssh package.json starknet:$WORKDIR
        shell: bash

      - name: Run deploy script
        run: |
          ssh starknet "cd $WORKDIR && ./deploy"
